#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define ERROR_NO_EEPROM_DATA 2
#define ERROR_FIRMWARE_NOT_COMPATIBLE_WITH_PCB 3
#define ERROR_MISSING_CELLS 4
#define ERROR_TEMP_TOO_HIGH 5
#define ERROR_TEMP_TOO_LOW 6
#define ERROR_TEMP_DONT_MATCH 7
#define ERROR_MISSING_THERMAL_SWITCH 8 // TODO
#define ERROR_MISSING_TEMP_HUMIDITY_SENSOR 9
#define ERROR_MISSING_BQ25798 10
#define ERROR_MISSING_BQ76920 11
#define ERROR_TEMP_READING_FAILED 12

#endif
